# Generated by Django 4.0.4 on 2022-05-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_bids', '0002_alter_bids_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='user_id',
            new_name='buyer_id',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='product_id',
            new_name='listing_id',
        ),
    ]
