# Generated by Django 4.0.4 on 2022-05-12 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_bids', '0002_alter_bids_user_id'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('checkout', '0002_alter_cart_user_id_alter_payment_user_id'),
        ('userprofile', '0004_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('image', models.CharField(default='https://d25tv1xepz39hi.cloudfront.net/2016-07-16/files/cat-sample_1313.jpg', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
