# Generated by Django 4.0.4 on 2022-05-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_remove_userinfo_user_id_userinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
