# Generated by Django 4.0.4 on 2022-05-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_userinfo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
