# Generated by Django 4.0.4 on 2022-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_alter_userinfo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
