# Generated by Django 4.0.4 on 2022-05-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('listing_description', models.CharField(max_length=500)),
                ('listing_condition', models.IntegerField()),
                ('listing_price', models.FloatField()),
                ('listing_highest_offer', models.CharField(max_length=30)),
                ('listing_image_url', models.CharField(default='https://d25tv1xepz39hi.cloudfront.net/2016-07-16/files/cat-sample_1313.jpg', max_length=500)),
                ('listing_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.listingcategory')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.user')),
            ],
        ),
    ]
