# Generated by Django 4.0.4 on 2022-05-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default = '2020-05-08'),
        ),
    ]
