# Generated by Django 4.0.4 on 2022-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_listings', '0003_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
