# Generated by Django 4.0.4 on 2022-05-09 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_listings', '0004_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
