# Generated by Django 4.0.4 on 2022-05-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_listings', '0005_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_image_url',
            field=models.CharField(max_length=500),
        ),
    ]
