# Generated by Django 4.0.4 on 2022-05-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_listings', '0010_alter_listing_listing_highest_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_sold',
            field=models.BooleanField(default=False),
        ),
    ]
